[profile.default]
src = "src"
out = "out"
libs = ["lib"]
auto_detect_remappings = true
remappings = [
    '@chronicle/=src/',
    '@chronicle-test/=test/',
    '@chronicle-script/=script/',
    '@chronicle-types/=src/libraries/types/',
    '@chronicle-logs/=src/libraries/logs/',
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    'hedera-token-service/=lib/hedera-smart-contracts/contracts/system-contracts/hedera-token-service/',
    'hedera-system-contracts/=lib/hedera-smart-contracts/contracts/system-contracts/'
]
ffi = true
optimizer_runs = 1_000_000

[rpc_endpoints]
testnet = "${TEST_RPC_URL}"
previewnet = "${PRE_RPC_URL}"
